[theme]
name = 'XCursor-Pro-Regular'
comment = 'Modern, Proffesional Regular Windows Cursors'
website = 'https://github.com/ful1e5/XCursor-pro'

[config]
bitmaps_dir = ''   # This config will assigned with `ctgen -d <path>`
out_dir = '../themes'
platforms = 'windows'


[cursors]
[cursors.fallback_settings]
win_sizes = ["22:32", "32:48", "43:64", "64:96", "86:128"]
x_hotspot = 128
y_hotspot = 128
win_delay = 1


[cursors.all-scroll]
png = 'all-scroll.png'
win_name = 'Move'

[cursors.move]
png = 'move.png'
x_hotspot = 137
y_hotspot = 84
win_name = 'Grabbing'

[cursors.bottom_left_corner]
png = 'bottom_left_corner.png'
win_name = 'Dgn2'

[cursors.bottom_right_corner]
png = 'bottom_right_corner.png'
win_name = 'Dgn1'

[cursors.cross]
png = 'cross.png'
win_name = 'Cross'

[cursors.crossed_circle]
png = 'crossed_circle.png'
x_hotspot = 39
y_hotspot = 32
win_name = 'Unavailable'

[cursors.hand1]
png = 'hand1.png'
x_hotspot = 141
y_hotspot = 88
win_name = 'Pan'

[cursors.hand2]
png = 'hand2.png'
x_hotspot = 98
y_hotspot = 24
win_name = 'Link'

[cursors.left_ptr]
png = 'left_ptr.png'
x_hotspot = 123
y_hotspot = 11
win_name = 'Pointer'

[cursors.left_ptr_watch]
png = 'left_ptr_watch-*.png'
x_hotspot = 40
y_hotspot = 30
win_sizes = "64:96"
win_name = 'Work'

[cursors.pencil]
png = 'pencil.png'
x_hotspot = 28
y_hotspot = 226
win_name = 'Handwriting'

[cursors.question_arrow]
png = 'question_arrow.png'
x_hotspot = 39
y_hotspot = 32
win_name = 'Help'

[cursors.right_ptr]
png = 'right_ptr.png'
x_hotspot = 174
y_hotspot = 42
win_name = 'Alternate'

[cursors.sb_h_double_arrow]
png = 'sb_h_double_arrow.png'
x11_name = 'sb_h_double_arrow'
win_name = 'Horz'

[cursors.sb_v_double_arrow]
png = 'sb_v_double_arrow.png'
win_name = 'Vert'

[cursors.wait]
png = 'wait-*.png'
win_sizes = "64:96"
win_name = 'Busy'

[cursors.xterm]
png = 'xterm.png'
x_hotspot = 128
y_hotspot = 126
win_name = 'Text'

[cursors.zoom-in]
png = 'zoom-in.png'
x_hotspot = 112
y_hotspot = 113
win_name = 'Zoom-in'

[cursors.zoom-out]
png = 'zoom-out.png'
x_hotspot = 112
y_hotspot = 113
win_name = 'Zoom-out'

[cursors.person]
png = 'person.png'
x_hotspot = 39
y_hotspot = 32
win_name = 'Person'

[cursors.pin]
png = 'pin.png'
x_hotspot = 39
y_hotspot = 32
win_name = 'Pin'
